obj-$(CONFIG_SILEAD_FP)				+= silead/
obj-$(CONFIG_SUNWAVE_FP)			+= sunwave/
obj-$(CONFIG_CDFINGER_FP)			+= cdfinger/
obj-$(CONFIG_GOODIX_GFX18M) 			+= goodix_gfx18m/
obj-$(CONFIG_INPUT_GF5288) 			+= goodix_gf5288/
